package br.com.zup.movieflix

const val PREFERENCE_KEY = "br.com.zup.movieflix.PREFERENCE_KEY"
const val SAVE_USER_PASS_FLAG_KEY = "br.com.zup.movieflix.SAVE_USER_PASS_FLAG_KEY"
const val USER_NAME_LOGIN_KEY = "br.com.zup.movieflix.USER_NAME_LOGIN_KEY"
const val USER_PASSWORD_LOGIN_KEY = "br.com.zup.movieflix.USER_PASSWORD_LOGIN_KEY"
const val CHAVE_MOVIE = "CHAVE_MOVIE"
const val PULP_FICTION = " Pulp Fiction"
const val PULP_FICTION_SINOPSE = "Assassino que trabalha para a máfia se apaixona pela esposa de seu chefe quando é convidado a acompanhá-la, um boxeador descumpre sua promessa de perder uma luta e um casal tenta um assalto que rapidamente sai do controle."
const val DJANGO = " DJango"
const val DJANGO_SINOPSE = "No sul dos Estados Unidos, o ex-escravo Django faz uma aliança inesperada com o caçador de recompensas Schultz para caçar os criminosos mais procurados do país e resgatar sua esposa de um fazendeiro que força seus escravos a participar de competições mortais."
const val RESEVOIR_DOGS = " Cães de Aluguel"
const val RESEVOIR_DOGS_SINOPSE = "Criminoso reúne seis bandidos para grande roubo de diamantes. Algo sai errado e um deles é ferido durante roubo e os bandidos precisam descobrir quem foi que os traiu, o que gera enorme tensão no grupo e enfraquece a todos."
const val GOODFELLAS = " Os Bons Companheiros"
const val GOODFELLAS_SINOPSE = "Um jovem cresce na máfia e trabalha arduamente para crescer entre seus companheiros. Ele gosta da vida de dinheiro e luxo, mas não liga para o horror que provoca. Infelizmente, a dependência de drogas e alguns erros finalmente destroem sua escalada até o topo. Baseado no livro Wiseguy por Nicholas Pileggi."
const val TAXI_DRIVER = " Taxi Driver"
const val TAXI_DRIVER_SINOPSE = "O motorista de táxi de Nova York Travis Bickle, veterano da Guerra do Vietnã, reflete constantemente sobre a corrupção da vida ao seu redor e sente-se cada vez mais perturbado com a própria solidão e alienação. Apesar de não conseguir fazer contato emocional com ninguém e viver uma vida questionável em busca de diversão, ele se torna obcecado em ajudar uma prostituta de 12 anos que entra em seu táxi para fugir de um cafetão."
const val WOLF_WALLSTREET = " O Lobo de Wall Street"
const val WOLF_WALLSTREET_SINOPSE = "Jordan Belfort é um ambicioso corretor da bolsa de valores que cria um verdadeiro império, enriquecendo de forma rápida, porém ilegal. Ele e seus amigos mergulham em um mundo de excessos, mas seus métodos ilícitos despertam a atenção da polícia."
const val TARANTINO = " Quentin Tarantino"
const val TARANTINO_INFO = "Quentin Jerome Tarantino é um realizador, argumentista, produtor, ator, diretor de fotografia e crítico de cinema americano. É vencedor de dois Oscars de Melhor Roteiro Original e foi eleito o 19° maior diretor de cinema dos últimos 25 anos segundo o levantamento da Quartz através do Metacritic."
const val MARTIN_SCORSESE = " Martin Scorsese"
const val MARTIN_SCORSESE_INFO = "Martin Scorsese (Queens, Nova Iorque, 17 de novembro de 1942) é um cineasta, produtor de cinema, roteirista e ator norte-americano vencedor do Oscar de melhor diretor por Os Infiltrados. \nEm 2002, foi eleito o nono maior diretor de cinema de todos os tempos em uma pesquisa realizada pelo British Film Institute e a revista Sight & Sound"